version: "3.9"
services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  neo4j:
    image: neo4j:5.26-community
    container_name: neo4j
    ports:
      - "7474:7474"   # HTTP
      - "7687:7687"   # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data

  app:
    build: .
    container_name: poultrygpt-app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - neo4j
    volumes:
      - ./data:/opt/data
      - ./m3e-small:/opt/m3e-small
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  redis_data:
  neo4j_data: